apiVersion: v1
kind: Service
metadata:
  name: my-load-balancer
spec:
  selector:
    hub.jupyter.org/username: daovietanh190499
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
  type: LoadBalancer
