apiVersion: v1
kind: Service
metadata:
  name: my-load-balancer
spec:
  selector:
    hub.jupyter.org/username: daovietanh190499
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5050
  type: LoadBalancer
