apiVersion: v1
kind: PersistentVolume
metadata:
  name: jupyter-linhlpv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: "/data/nas/jhub/jhub-linhlpv/"
    server: "10.1.8.99"
