apiVersion: v1
kind: PersistentVolume
metadata:
  name: jhub-vietbacnguyen96
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: "/data/nas/jhub/jhub-vietbacnguyen96"
    server: "10.1.8.99"
