apiVersion: v1
kind: Pod
metadata:
  name: test-gpu
spec:
  containers:
  - name: test-gpu
    image: nvidia/cuda:11.0-base
    #env:
    #- name: NVIDIA_VISIBLE_DEVICES
    #  value: 0,1
    #securityContext:
    #  capabilities:
    #    add: ['SYS_ADMIN']
    command: ['nvidia-smi', '-L']
    #command: ['echo', '$NVIDIA_VISIBLE_DEVICES']
    resources:
      limits:
        cpu: 8      
        nvidia.com/gpu: 1
